import type {
	GameCategory,
	GameDefinition,
	GameHelp,
	GameInstance,
	TouchLayout,
} from "@core/GameInterface";

/**
 * Helper: creates a lazy-loaded GameDefinition.
 * Metadata (name, icon, help, touchLayout) is static for instant menu rendering.
 * The actual game code is loaded via dynamic import() only when played.
 */
function lazyGame(
	id: string,
	name: string,
	description: string,
	icon: string,
	color: string,
	category: GameCategory,
	help: GameHelp,
	loader: () => Promise<{ default?: GameDefinition; [key: string]: unknown }>,
	exportName: string,
	touchLayout: TouchLayout = "tap-only",
): GameDefinition {
	return {
		id,
		name,
		description,
		icon,
		color,
		category,
		help,
		touchLayout,
		create(
			canvas: HTMLCanvasElement,
			onExit: () => void,
		): Promise<GameInstance> {
			return loader().then((mod) => {
				const def = (mod[exportName] ?? mod.default) as GameDefinition;

				return def.create(canvas, onExit) as GameInstance;
			});
		},
	};
}

// ─── Game metadata (static, no code loaded) ──────────────────────────────────

export const GAME_REGISTRY: Record<GameCategory, GameDefinition[]> = {
	arcade: [
		lazyGame(
			"snake",
			"Snake",
			"Eat food, grow longer!",
			"🐍",
			"#4ade80",
			"arcade",
			{
				goal: "Eat food to grow longer without hitting walls or yourself.",
				controls: [
					{ key: "Arrow Keys / WASD", action: "Change direction" },
					{ key: "P", action: "Pause" },
					{ key: "ESC", action: "Exit" },
				],
				tips: ["Plan your path ahead", "Speed increases as you eat"],
			},
			() => import("@games/snake"),
			"SnakeGame",
			"dpad",
		),
		lazyGame(
			"breakout",
			"Breakout",
			"Break all the bricks!",
			"🧱",
			"#e74c3c",
			"arcade",
			{
				goal: "Break all bricks by bouncing the ball off your paddle.",
				controls: [
					{ key: "Mouse", action: "Move paddle" },
					{ key: "Click", action: "Launch ball" },
					{ key: "ESC", action: "Exit" },
				],
				tips: ["Catch powerups", "Aim for corners"],
			},
			() => import("@games/breakout"),
			"BreakoutGame",
		),
		lazyGame(
			"asteroids",
			"Asteroids",
			"Destroy asteroids, survive!",
			"🚀",
			"#9b59b6",
			"arcade",
			{
				goal: "Destroy all asteroids without getting hit.",
				controls: [
					{ key: "Left/Right", action: "Rotate" },
					{ key: "Up", action: "Thrust" },
					{ key: "Space", action: "Shoot" },
				],
				tips: ["Large rocks split into smaller ones", "Use momentum"],
			},
			() => import("@games/asteroids"),
			"AsteroidsGame",
			"dpad-action",
		),
		lazyGame(
			"space-invaders",
			"Space Invaders",
			"Defend Earth!",
			"👾",
			"#e67e22",
			"arcade",
			{
				goal: "Destroy all aliens before they reach the ground.",
				controls: [
					{ key: "Left/Right", action: "Move" },
					{ key: "Space", action: "Shoot" },
				],
				tips: ["Aliens speed up as fewer remain", "Use shields wisely"],
			},
			() => import("@games/space-invaders"),
			"SpaceInvadersGame",
			"dpad-action",
		),
		lazyGame(
			"flappy-bird",
			"Flappy Bird",
			"Tap to flap through pipes!",
			"🐦",
			"#f1c40f",
			"arcade",
			{
				goal: "Fly through pipe gaps without hitting them.",
				controls: [{ key: "Space / Click", action: "Flap" }],
				tips: ["Small frequent taps give more control"],
			},
			() => import("@games/flappy-bird"),
			"FlappyBirdGame",
			"flap",
		),
		lazyGame(
			"tetris",
			"Tetris",
			"Classic block-stacking!",
			"🟦",
			"#00bcd4",
			"arcade",
			{
				goal: "Clear lines by filling complete rows.",
				controls: [
					{ key: "Left/Right", action: "Move" },
					{ key: "Up", action: "Rotate" },
					{ key: "Down", action: "Soft drop" },
					{ key: "Space", action: "Hard drop" },
				],
				tips: ["Clear 4 lines at once for Tetris bonus"],
			},
			() => import("@games/tetris"),
			"TetrisGame",
			"dpad-action",
		),
		lazyGame(
			"whack-a-mole",
			"Whack-a-Mole",
			"Timed reflex clicking!",
			"🔨",
			"#8d6e63",
			"arcade",
			{
				goal: "Whack moles before they hide. Avoid bombs.",
				controls: [{ key: "Click", action: "Whack" }],
				tips: ["Combo multiplier for consecutive hits"],
			},
			() => import("@games/whack-a-mole"),
			"WhackAMoleGame",
		),
		lazyGame(
			"helicopter",
			"Helicopter",
			"One-button cave scroller!",
			"🚁",
			"#66bb6a",
			"arcade",
			{
				goal: "Fly through the cave without crashing.",
				controls: [
					{ key: "Hold Space/Click", action: "Rise" },
					{ key: "Release", action: "Fall" },
				],
				tips: ["Cave narrows over time"],
			},
			() => import("@games/helicopter"),
			"HelicopterGame",
			"flap",
		),
		lazyGame(
			"pong",
			"Pong",
			"Paddle tennis vs AI!",
			"🏓",
			"#26c6da",
			"arcade",
			{
				goal: "Score 11 points by getting the ball past your opponent.",
				controls: [
					{ key: "W/S", action: "Left paddle" },
					{ key: "Up/Down", action: "Right paddle" },
				],
				tips: ["Ball speeds up each rally"],
			},
			() => import("@games/pong"),
			"PongGame",
			"dpad",
		),
		lazyGame(
			"pacman",
			"Pac-Man",
			"Eat dots, avoid ghosts!",
			"👻",
			"#ffeb3b",
			"arcade",
			{
				goal: "Eat all dots. Power pellets let you eat ghosts.",
				controls: [{ key: "Arrow Keys", action: "Move" }],
				tips: ["Each ghost has a different chase behavior"],
			},
			() => import("@games/pacman"),
			"PacManGame",
			"dpad",
		),
		lazyGame(
			"doodle-jump",
			"Doodle Jump",
			"Endless vertical jumping!",
			"🐸",
			"#66bb6a",
			"arcade",
			{
				goal: "Jump as high as possible.",
				controls: [{ key: "Left/Right", action: "Move" }],
				tips: ["Brown platforms break", "Red springs give super jumps"],
			},
			() => import("@games/doodle-jump"),
			"DoodleJumpGame",
			"dpad-jump",
		),
		lazyGame(
			"rhythm-tap",
			"Rhythm Tap",
			"Tap circles in time!",
			"🎵",
			"#e040fb",
			"arcade",
			{
				goal: "Click circles when the rings align.",
				controls: [{ key: "Click", action: "Tap" }],
				tips: ["Perfect timing = 300 points"],
			},
			() => import("@games/rhythm-tap"),
			"RhythmTapGame",
		),
		lazyGame(
			"reaction-timer",
			"Reaction Timer",
			"Test your reflexes!",
			"⏱️",
			"#ff5722",
			"arcade",
			{
				goal: "Click as fast as you can when the screen turns green.",
				controls: [{ key: "Click / Space", action: "React" }],
				tips: ["Don't click on red — that's too early"],
			},
			() => import("@games/reaction-timer"),
			"ReactionTimerGame",
		),
		lazyGame(
			"balloon-pop",
			"Balloon Pop",
			"Pop balloons!",
			"🎈",
			"#e91e63",
			"arcade",
			{
				goal: "Click balloons before they escape. 90 seconds.",
				controls: [{ key: "Click", action: "Pop" }],
				tips: ["Smaller balloons = more points"],
			},
			() => import("@games/balloon-pop"),
			"BalloonPopGame",
		),
		lazyGame(
			"color-switch",
			"Color Switch",
			"Match the colors!",
			"🎨",
			"#e040fb",
			"arcade",
			{
				goal: "Pass through gate sections matching your ball's color.",
				controls: [{ key: "Space / Click", action: "Bounce" }],
				tips: ["Color switchers change your ball's color"],
			},
			() => import("@games/color-switch"),
			"ColorSwitchGame",
			"flap",
		),
		lazyGame(
			"typing-speed",
			"Typing Speed",
			"Type falling words!",
			"⌨️",
			"#00897b",
			"arcade",
			{
				goal: "Type words before they reach the bottom.",
				controls: [{ key: "A-Z", action: "Type" }],
				tips: ["Auto-targets the closest matching word"],
			},
			() => import("@games/typing-speed"),
			"TypingSpeedGame",
		),
		lazyGame(
			"frogger",
			"Frogger",
			"Cross roads and rivers!",
			"🐸",
			"#4caf50",
			"arcade",
			{
				goal: "Cross 5 road lanes and 5 river lanes to reach the top.",
				controls: [{ key: "Arrow Keys", action: "Hop" }],
				tips: ["Ride logs on the river", "Reach all 5 lily pads"],
			},
			() => import("@games/frogger"),
			"FroggerGame",
			"dpad",
		),
	],
	action: [
		lazyGame(
			"tower-defense",
			"Tower Defense",
			"Place towers, survive waves!",
			"🏰",
			"#2ecc71",
			"action",
			{
				goal: "Place towers to destroy enemies before they reach the exit.",
				controls: [
					{ key: "Click", action: "Place/select tower" },
					{ key: "Space", action: "Start wave" },
					{ key: "P", action: "Pause" },
				],
				tips: [
					"Frost towers slow enemies",
					"Upgrade for 2.5x damage at level 3",
				],
			},
			() => import("@games/tower-defense"),
			"TowerDefenseGame",
		),
		lazyGame(
			"platformer",
			"Platformer",
			"Jump, collect coins!",
			"🏃",
			"#60a5fa",
			"action",
			{
				goal: "Reach the flag. Collect coins and stomp enemies.",
				controls: [
					{ key: "Arrow Keys / WASD", action: "Move" },
					{ key: "Space", action: "Jump" },
				],
				tips: ["Jump on enemies to stomp them"],
			},
			() => import("@games/platformer"),
			"PlatformerGame",
			"dpad-jump",
		),
		lazyGame(
			"topdown-shooter",
			"Top-Down Shooter",
			"WASD + mouse aim!",
			"🔫",
			"#e53935",
			"action",
			{
				goal: "Survive waves of enemies in an arena.",
				controls: [
					{ key: "WASD", action: "Move" },
					{ key: "Mouse", action: "Aim" },
					{ key: "Click", action: "Shoot" },
				],
				tips: ["Different enemy types: fast, tank, ranged"],
			},
			() => import("@games/topdown-shooter"),
			"TopDownShooterGame",
			"dual-stick",
		),
		lazyGame(
			"zombie-survival",
			"Zombie Survival",
			"Survive the night!",
			"🧟",
			"#27ae60",
			"action",
			{
				goal: "Survive zombie waves. Scavenge by day, fight by night.",
				controls: [
					{ key: "WASD", action: "Move" },
					{ key: "Click", action: "Shoot" },
					{ key: "E", action: "Place barricade" },
				],
				tips: ["Build barricades during daytime"],
			},
			() => import("@games/zombie-survival"),
			"ZombieSurvivalGame",
			"dual-stick",
		),
		lazyGame(
			"racing",
			"Racing",
			"Top-down racing!",
			"🏎️",
			"#ff5722",
			"action",
			{
				goal: "Complete 3 laps before AI opponents.",
				controls: [
					{ key: "Up/Down", action: "Accelerate/brake" },
					{ key: "Left/Right", action: "Steer" },
				],
				tips: ["Going off-track slows you down"],
			},
			() => import("@games/racing"),
			"RacingGame",
			"dpad",
		),
		lazyGame(
			"fruit-ninja",
			"Fruit Ninja",
			"Slice fruit!",
			"🍉",
			"#e91e63",
			"action",
			{
				goal: "Slice fruit, avoid bombs. 3 lives.",
				controls: [{ key: "Mouse drag", action: "Slice" }],
				tips: ["Combo bonus for multiple slices in one swipe"],
			},
			() => import("@games/fruit-ninja"),
			"FruitNinjaGame",
			"none",
		),
		lazyGame(
			"lava-floor",
			"Lava Floor",
			"Don't fall in!",
			"🌋",
			"#ff5722",
			"action",
			{
				goal: "Jump between sinking platforms. Survive as long as possible.",
				controls: [
					{ key: "Left/Right", action: "Move" },
					{ key: "Space", action: "Jump" },
				],
				tips: ["Platforms sink 2 seconds after landing"],
			},
			() => import("@games/lava-floor"),
			"LavaFloorGame",
			"dpad-jump",
		),
		lazyGame(
			"basketball",
			"Basketball",
			"Shoot hoops!",
			"🏀",
			"#ff7043",
			"action",
			{
				goal: "Drag to aim, release to shoot. 30-second shot clock.",
				controls: [{ key: "Click+drag", action: "Aim & shoot" }],
				tips: ["Streak bonus for consecutive makes"],
			},
			() => import("@games/basketball"),
			"BasketballGame",
			"none",
		),
		lazyGame(
			"golf",
			"Golf",
			"Mini golf, 9 holes!",
			"⛳",
			"#388e3c",
			"action",
			{
				goal: "Putt the ball into the hole in as few strokes as possible.",
				controls: [{ key: "Click+drag", action: "Aim & putt" }],
				tips: ["Drag opposite direction to aim"],
			},
			() => import("@games/golf"),
			"GolfGame",
			"none",
		),
	],
	puzzle: [
		lazyGame(
			"physics-puzzle",
			"Physics Puzzle",
			"Simulate physics!",
			"🧩",
			"#f59e0b",
			"puzzle",
			{
				goal: "Place pieces to guide the ball to the star.",
				controls: [
					{ key: "Click", action: "Place piece" },
					{ key: "Space", action: "Simulate" },
					{ key: "R", action: "Reset" },
				],
				tips: ["Use ramps to redirect the ball"],
			},
			() => import("@games/physics-puzzle"),
			"PhysicsPuzzleGame",
		),
		lazyGame(
			"minesweeper",
			"Minesweeper",
			"Reveal cells, flag mines!",
			"💣",
			"#95a5a6",
			"puzzle",
			{
				goal: "Reveal all safe cells without hitting a mine.",
				controls: [
					{ key: "Click", action: "Reveal" },
					{ key: "Right-click", action: "Flag" },
				],
				tips: [
					"First click is always safe",
					"Numbers show adjacent mine count",
				],
			},
			() => import("@games/minesweeper"),
			"MinesweeperGame",
		),
		lazyGame(
			"match3",
			"Match-3",
			"Swap gems, cascade combos!",
			"💎",
			"#e91e63",
			"puzzle",
			{
				goal: "Swap adjacent gems to match 3+ in a row. 30 moves.",
				controls: [{ key: "Click", action: "Select & swap" }],
				tips: ["Cascading matches multiply your score"],
			},
			() => import("@games/match3"),
			"Match3Game",
		),
		lazyGame(
			"game-2048",
			"2048",
			"Slide & merge tiles!",
			"🔢",
			"#ff9800",
			"puzzle",
			{
				goal: "Merge tiles to reach 2048.",
				controls: [{ key: "Arrow Keys", action: "Slide" }],
				tips: ["Keep your highest tile in a corner"],
			},
			() => import("@games/game-2048"),
			"Game2048",
			"dpad",
		),
		lazyGame(
			"sokoban",
			"Sokoban",
			"Push boxes onto targets!",
			"📦",
			"#795548",
			"puzzle",
			{
				goal: "Push all boxes onto target squares.",
				controls: [
					{ key: "Arrow Keys", action: "Move/push" },
					{ key: "Z", action: "Undo" },
					{ key: "R", action: "Restart" },
				],
				tips: ["You can't pull boxes — plan ahead"],
			},
			() => import("@games/sokoban"),
			"SokobanGame",
			"dpad",
		),
		lazyGame(
			"maze-runner",
			"Maze Runner",
			"Escape the maze!",
			"🏃‍♂️",
			"#607d8b",
			"puzzle",
			{
				goal: "Navigate through a procedural maze before time runs out.",
				controls: [{ key: "Arrow Keys / WASD", action: "Move" }],
				tips: ["Fog of war — only see 3 cells around you"],
			},
			() => import("@games/maze-runner"),
			"MazeRunnerGame",
			"dpad",
		),
		lazyGame(
			"word-search",
			"Word Search",
			"Find hidden words!",
			"🔤",
			"#5c6bc0",
			"puzzle",
			{
				goal: "Find all 8 hidden words in the letter grid.",
				controls: [{ key: "Click+drag", action: "Select word" }],
				tips: ["Words can go in any direction, including diagonal"],
			},
			() => import("@games/word-search"),
			"WordSearchGame",
		),
		lazyGame(
			"sudoku",
			"Sudoku",
			"Number placement puzzle!",
			"🔢",
			"#7e57c2",
			"puzzle",
			{
				goal: "Fill every row, column, and 3x3 box with 1-9.",
				controls: [
					{ key: "Click", action: "Select cell" },
					{ key: "1-9", action: "Place number" },
					{ key: "N", action: "Notes mode" },
				],
				tips: ["Use notes mode to track candidates"],
			},
			() => import("@games/sudoku"),
			"SudokuGame",
		),
		lazyGame(
			"pipe-connect",
			"Pipe Connect",
			"Connect the flow!",
			"🔧",
			"#26a69a",
			"puzzle",
			{
				goal: "Rotate pipes to connect source to drain.",
				controls: [{ key: "Click", action: "Rotate pipe" }],
				tips: ["Water flows through connected openings"],
			},
			() => import("@games/pipe-connect"),
			"PipeConnectGame",
		),
		lazyGame(
			"lights-out",
			"Lights Out",
			"Toggle all lights off!",
			"💡",
			"#ffca28",
			"puzzle",
			{
				goal: "Turn all lights off. Clicking toggles adjacent lights too.",
				controls: [{ key: "Click", action: "Toggle" }],
				tips: ["Work from one corner systematically"],
			},
			() => import("@games/lights-out"),
			"LightsOutGame",
		),
		lazyGame(
			"memory-match",
			"Memory Match",
			"Find matching pairs!",
			"🃏",
			"#ab47bc",
			"puzzle",
			{
				goal: "Flip cards to find matching pairs.",
				controls: [{ key: "Click", action: "Flip card" }],
				tips: ["Remember card positions as they're revealed"],
			},
			() => import("@games/memory-match"),
			"MemoryMatchGame",
		),
		lazyGame(
			"simon-says",
			"Simon Says",
			"Repeat the sequence!",
			"🟢",
			"#4caf50",
			"puzzle",
			{
				goal: "Repeat the growing color sequence.",
				controls: [{ key: "Click", action: "Select color" }],
				tips: ["Speed increases each round"],
			},
			() => import("@games/simon-says"),
			"SimonSaysGame",
		),
		lazyGame(
			"gravity-ball",
			"Gravity Ball",
			"Change gravity!",
			"⚫",
			"#78909c",
			"puzzle",
			{
				goal: "Toggle gravity direction to guide the ball to the exit.",
				controls: [
					{ key: "Arrow Keys", action: "Change gravity" },
					{ key: "R", action: "Reset" },
				],
				tips: ["Ball rolls until hitting a wall"],
			},
			() => import("@games/gravity-ball"),
			"GravityBallGame",
			"dpad",
		),
		lazyGame(
			"hangman",
			"Hangman",
			"Guess the word!",
			"📝",
			"#8d6e63",
			"puzzle",
			{
				goal: "Guess the word before 6 wrong guesses.",
				controls: [{ key: "A-Z", action: "Guess letter" }],
				tips: ["Category is shown as a hint"],
			},
			() => import("@games/hangman"),
			"HangmanGame",
		),
	],
	strategy: [
		lazyGame(
			"city-builder",
			"City Builder",
			"Build your city!",
			"🏙️",
			"#3498db",
			"strategy",
			{
				goal: "Build a thriving city managing population, food, power, happiness.",
				controls: [
					{ key: "1-6", action: "Select building" },
					{ key: "Click", action: "Place" },
				],
				tips: [
					"Parks boost happiness",
					"Factories generate income but reduce happiness",
				],
			},
			() => import("@games/city-builder"),
			"CityBuilderGame",
		),
		lazyGame(
			"card-battle",
			"Card Battle",
			"Defeat AI enemies!",
			"🃏",
			"#8e44ad",
			"strategy",
			{
				goal: "Play attack/defense/heal cards to defeat 3 enemy rounds.",
				controls: [{ key: "Click", action: "Play card" }],
				tips: ["3 energy per turn — plan your plays"],
			},
			() => import("@games/card-battle"),
			"CardBattleGame",
		),
		lazyGame(
			"ant-colony",
			"Ant Colony",
			"Manage your colony!",
			"🐜",
			"#6d4c41",
			"strategy",
			{
				goal: "Manage ants gathering food and building tunnels. Survive winter.",
				controls: [
					{ key: "Click", action: "Place food" },
					{ key: "Right-click", action: "Dig tunnel" },
				],
				tips: ["Build food reserves before winter"],
			},
			() => import("@games/ant-colony"),
			"AntColonyGame",
		),
		lazyGame(
			"tic-tac-toe",
			"Tic-Tac-Toe",
			"Unbeatable AI!",
			"❌",
			"#ef5350",
			"strategy",
			{
				goal: "Get 3 in a row on a 3x3 grid.",
				controls: [{ key: "Click", action: "Place mark" }],
				tips: ["The AI uses minimax — it can't be beaten!"],
			},
			() => import("@games/tic-tac-toe"),
			"TicTacToeGame",
		),
		lazyGame(
			"connect-four",
			"Connect Four",
			"Drop discs, connect 4!",
			"🔴",
			"#e53935",
			"strategy",
			{
				goal: "Connect 4 discs in a row (horizontal/vertical/diagonal).",
				controls: [{ key: "Click column", action: "Drop disc" }],
				tips: ["Control the center column"],
			},
			() => import("@games/connect-four"),
			"ConnectFourGame",
		),
		lazyGame(
			"chess",
			"Chess",
			"Full rules, minimax AI!",
			"♟️",
			"#5d4037",
			"strategy",
			{
				goal: "Checkmate your opponent's king.",
				controls: [{ key: "Click", action: "Select & move piece" }],
				tips: ["Control the center", "Castle early for king safety"],
			},
			() => import("@games/chess"),
			"ChessGame",
		),
		lazyGame(
			"checkers",
			"Checkers",
			"Forced captures, king me!",
			"🔴",
			"#b71c1c",
			"strategy",
			{
				goal: "Capture all opponent pieces or block their moves.",
				controls: [{ key: "Click", action: "Select & move" }],
				tips: ["Jumps are mandatory", "Kings can move backwards"],
			},
			() => import("@games/checkers"),
			"CheckersGame",
		),
	],
	chill: [
		lazyGame(
			"fishing",
			"Fishing",
			"Cast, hook, reel!",
			"🎣",
			"#0288d1",
			"chill",
			{
				goal: "Catch fish! Cast, time the hook, keep tension in the green zone.",
				controls: [{ key: "Space", action: "Cast / Hook / Reel" }],
				tips: ["Longer casts find rarer fish"],
			},
			() => import("@games/fishing"),
			"FishingGame",
			"none",
		),
		lazyGame(
			"idle-clicker",
			"Idle Clicker",
			"Click & upgrade!",
			"💰",
			"#ffc107",
			"chill",
			{
				goal: "Click to earn coins, buy upgrades, automate.",
				controls: [{ key: "Click", action: "Earn coins" }],
				tips: ["Progress saves automatically"],
			},
			() => import("@games/idle-clicker"),
			"IdleClickerGame",
		),
		lazyGame(
			"particle-sand",
			"Particle Sand",
			"Sand/water/fire sandbox!",
			"🏖️",
			"#ffb74d",
			"chill",
			{
				goal: "Draw with falling sand, water, and fire. No rules!",
				controls: [
					{ key: "Click+drag", action: "Place particles" },
					{ key: "1-5", action: "Select material" },
				],
				tips: ["Water + fire = steam"],
			},
			() => import("@games/particle-sand"),
			"ParticleSandGame",
		),
		lazyGame(
			"brick-builder",
			"Brick Builder",
			"Creative stacking!",
			"🧱",
			"#ff7043",
			"chill",
			{
				goal: "Build anything! Snap bricks to the grid.",
				controls: [
					{ key: "Click", action: "Place brick" },
					{ key: "Right-click", action: "Remove" },
				],
				tips: ["Gravity pulls bricks down"],
			},
			() => import("@games/brick-builder"),
			"BrickBuilderGame",
		),
		lazyGame(
			"pixel-art",
			"Pixel Art",
			"Draw pixel art!",
			"🎨",
			"#9c27b0",
			"chill",
			{
				goal: "Draw pixel art on a grid with 16 colors.",
				controls: [
					{ key: "Click", action: "Draw" },
					{ key: "Right-click", action: "Erase" },
					{ key: "F", action: "Fill" },
				],
				tips: ["Use eyedropper (I) to pick colors from your art"],
			},
			() => import("@games/pixel-art"),
			"PixelArtGame",
		),
	],
	"3d": [],
};

/** Flat list of all games across categories */
export function getAllGames(): GameDefinition[] {
	return Object.values(GAME_REGISTRY).flat();
}

/** Get games for a specific category */
export function getGamesByCategory(category: GameCategory): GameDefinition[] {
	return GAME_REGISTRY[category];
}
